### ISSUE TITLE
Would the library have further development and support?

### ISSUE THREAD

**Issue by Alkenso** [x13a/libproc-swift#1]
I like such approach making the life easier dealing with system stuff in Swift
Would the library have further development and support?

**Comment by x13a** [comment]
It depends. Are you missing something? If you need something more I may
take a look. PR's are welcome too.

**Comment by x13a** [comment]
Closing on inactivity

**Comment by Alkenso** [comment]
Thanks for reply. Checking if repo is active, b/c like to use in in production =)
