### ISSUE TITLE
Check ports used?

### ISSUE THREAD

**Issue by jeff-h** [x13a/libproc-swift#2]
Hi — I'm wondering if this library can list which (TCP) ports are in use by any given PID?

**Comment by x13a** [comment]
Hi,

Suppose yes, please take a look at the C example: https://github.com/palominolabs/get_process_handles/blob/master/main.c

**Comment by jeff-h** [comment]
Thanks for your reply! I am wondering if this is something you would consider adding to libproc-swift?

**Comment by x13a** [comment]
All required functions already here, you have to repeat steps in swift from the C example.

`proc_pidinfo` to list pid fds
`proc_pidfdinfo` to get fd socket info

**Comment by jeff-h** [comment]
Greatly appreciate your help! I've tried:

```swift
let fdInfo = try Proc.listPidInfo(list_proc_fdinfo.self, pid, 0).get()

try? fdInfo.forEach { fd in
    let filePortInfo = try Proc.pidFdInfo(fd_socket_fdinfo.self, pid, fd.proc_fd)
            
    print(filePortInfo.
}
```

There were many fd's, and several returned success from the above code, with results like this:

```
success(
	__C.socket_fdinfo(
		pfi: __C.proc_fileinfo(
			fi_openflags: 7,
			fi_status: 1,
			fi_offset: 0,
			fi_type: 2,
			fi_guardflags: 0
		),
		psi: __C.socket_info(
			soi_stat: __C.vinfo_stat(
				vst_dev: 0,
				vst_mode: 0,
				vst_nlink: 0,
				vst_ino: 0,
				vst_uid: 0,
				vst_gid: 0,
				vst_atime: 0,
				vst_atimensec: 0,
				vst_mtime: 0,
				vst_mtimensec: 0,
				vst_ctime: 0,
				vst_ctimensec: 0,
				vst_birthtime: 0,
				vst_birthtimensec: 0,
				vst_size: 0,
				vst_blocks: 0,
				vst_blksize: 0,
				vst_flags: 0,
				vst_gen: 0,
				vst_rdev: 0,
				vst_qspare: (
					0,
					0
				)
			),
			soi_so: 7034426511693411045,
			soi_pcb: 7034426511693411997,
			soi_type: 1,
			soi_protocol: 6,
			soi_family: 2,
			soi_options: 6,
			soi_linger: 0,
			soi_state: 384,
			soi_qlen: 0,
			soi_incqlen: 0,
			soi_qlimit: 128,
			soi_timeo: 0,
			soi_error: 0,
			soi_oobmark: 0,
			soi_rcv: __C.sockbuf_info(
				sbi_cc: 0,
				sbi_hiwat: 131072,
				sbi_mbcnt: 0,
				sbi_mbmax: 1048576,
				sbi_lowat: 1,
				sbi_flags: 1092,
				sbi_timeo: 0
			),
			soi_snd: __C.sockbuf_info(
				sbi_cc: 0,
				sbi_hiwat: 131072,
				sbi_mbcnt: 0,
				sbi_mbmax: 1048576,
				sbi_lowat: 2048,
				sbi_flags: 1024,
				sbi_timeo: 0
			),
			soi_kind: 2,
			rfu_1: 0,
			soi_proto: __C.socket_info.__Unnamed_union_soi_proto()
		)
	)
)
```

Should I be able to get the port Uint from the above? In your example C code, I saw they got it with `int localPort = (int)ntohs(socketInfo.psi.soi_proto.pri_tcp.tcpsi_ini.insi_lport);` but I lack the knowledge of how to write a swift equivalent :(

**Comment by x13a** [comment]
Hard to say without trying it myself. You can try `print(filePortInfo.psi.soi_proto.pri_tcp.tcpsi_ini.insi_lport)` after unwrapping the result of _filePortInfo_. But there may be a problem with `soi_proto: __C.socket_info.__Unnamed_union_soi_proto()`. Maybe additional conversation is needed.

**Comment by x13a** [comment]
Closing on inactivity

**Comment by x13a** [comment]
Hard to say without trying it myself. You can try
*print(filePortInfo.psi.soi_proto.pri_tcp.tcpsi_ini.insi_lport)
*after unwrapping the result of *filePortInfo**. *But there may be a
problem with *soi_proto: __C.socket_info.__Unnamed_union_soi_proto()**. *Maybe
additional conversation is needed.
