### ISSUE TITLE
Mark import of Clibproc as implementation-only

### ISSUE THREAD

**Issue by Alkenso** [x13a/libproc-swift#3]
In some scenarios, Xcode fails build because 'module Clibproc not found'.
It happens if resulting target indirectly contains another target that links with libproc package

To fix the things, please mark all imports of `Clibproc` with @_implementationOnly 

`@_implementationOnly import Clibproc`

**Comment by x13a** [comment]
Got it, will update after xcode 14.1 release.

**Comment by Alkenso** [comment]
ping

**Comment by x13a** [comment]
Hi @Alkenso , sorry for such a long delay. Is it actual now?

**Comment by Alkenso** [comment]
seems need to be re-tested with latest Xcode
probably with Swift 6 release we may mark it like `private import`

**Comment by x13a** [comment]
Done in recent update, get `cwd` test failed, will take a look later
